### ISSUE TITLE
Example using NATS for global sync of Sqlite DB in a CQRS pattern, Hosted with New

### ISSUE THREAD

**Issue by gedw99** [synadia-io/nex#211]
### Proposed change

https://github.com/maxpert/marmot
Marmot does SQLite db sync using NATS.

Add a provider to Marmot to use Nex. Not sure exactly best way yet.

Add example using it with NEX. https://github.com/maxpert/marmot-pocketbase-flyio Is a reference example that works well and so can reference this for the new example.

Make a new repo to host  the example.

Add Gateway and Super Cluster support too.

### Use case

Need a db that’s simple for a CQRS style setup and need it synced globally both inside data centers and at the edge. 

New now supports running non sandboxed on Mac and Win, so for Edge this works well for Orgs without any Linux boxes or experience.

**Comment by jordan-rash** [comment]
Thanks for the issue @gedw99.  While we would love to see this example, its currently outside the scope of our near/medium term roadmap.  We would encourage you to build this, and we can look at creating an Awesome Nex list with your work.  I will keep your [discussion](https://github.com/synadia-io/nex/discussions/212) on the topic open so that we can all collaborate on the idea there.

**Comment by gedw99** [comment]
sounds good. will let you know when its ready for eye balls :)

**Comment by hpvd** [comment]
just opened a discussion, somehow related to this:
plans to make it possible to also deploy and run databases using nex?
https://github.com/synadia-io/nex/discussions/447

**Comment by hpvd** [comment]
@gedw99 thanks for your explanation and details!
I was wondering, if one couldn't fully integrate a database the "native way" as storage type similar to already done with kv and blob storage...
see https://github.com/synadia-io/nex/discussions/447
