### ISSUE TITLE
Smarter Run Command | Node Queries

### ISSUE THREAD

**Issue by jordan-rash** [synadia-io/nex#239]
### Proposed change

Currently, when you try to deploy a workload, the nex binary does not validate that the node your sending to can support the particular workload you are providing.  This was originally an intentional design, as `no-sandbox` mode didn't exist and the target OS/Arch was much smaller.  Now, we have to ensure ELFs aren't sent to Windows, arm64 isnt send to arm64, etc.

This issue proposed asking a node if it is able to run a workload prior to tasking.  The "PING" endpoint currently has enough data to assist in this decision, but that puts the task of deciding on the CLI (CLI -> PING -> Parse Responses -> Deploy)

A better approach might be to send a request with details of the workload and have the nodes ACK/NACK if they can support.  This will enable us to go beyond native binaries and as nodes if they can support cetain workloads (not everything can support V8 for example)...tags, etc.

### Use case

Adds more protection to deploying workloads

Depends on: #234

**Comment by jordan-rash** [comment]
Work in #235 to be leveraged with this

**Comment by autodidaddict** [comment]
To add some more specific requirements to this, what we're describing here is the "auction" pattern (this pattern also goes by many other names). One thing with this pattern is we don't want to reuse existing `PING` endpoints because ping's contract implies that any listening node will/must reply. Auction candidates only reply if they meet the criteria.

I propose that we have another endpoint, `$NEX.AUCTION.{namespace}`. Namespace here implies the _intended_ namespace of the candidate workload. 

## Auction Request
Clients making an auction request should supply the following JSON:

```json
{
    "workload_name": "xxx",
    "workload_bytes": "xxx",
    "workload_type": "[v8|wasm|elf/native]",
    "required_tags": [],
}
```

All fields in this payload are required. If there are no required tags, pass an empty list `[]`. Only nodes that think they can run the expected workload candidate should reply. The reply doesn't matter, but it will be the string `OK` when in multi-node auction mode.

Note that we don't need a boolean flag here to indicate acceptance because the existence of a reply on its own constitutes an acceptance. There is _no_ reply to indicate a rejection by the node.

Reasons for rejection (non-response):
* Node has reached workload capacity (number)
* Node has reached workload capacity (bytes/resource consumption)
* Node type mismatch
* Node tags mismatch
* Workload with desired name is already running in the desired namespace on the target node

If you want the reason _why_ a _specific_ node does not want to run a workload (typically used when a UI or other consumer gets no positive replies to an auction), then you can re-run the auction request on the target node: `$NEX.AUCTION.{node_id}.{namespace}`. This will return the auction response payload shown below:

```json
{
    "accepted": [true|false],
    "rejections": [
         "string",
    ]
}
```
It's worth noting that the auction is a lightweight process. No actual workload bytes are submitted for auction, as those will be validated by the node during its real deployment process.
